# Generated by Django 5.0.7 on 2024-07-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmiratesTangermed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('heure_prelevement', models.TimeField()),
                ('administration', models.IntegerField()),
                ('cellule1', models.FloatField()),
                ('cellule2', models.FloatField()),
                ('mezannine', models.FloatField()),
                ('tgbt', models.FloatField()),
            ],
            options={
                'verbose_name': 'Emirates Tangermed',
                'verbose_name_plural': 'Emirates Tangermed',
            },
        ),
    ]
