# Generated by Django 5.0.7 on 2024-07-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emirate', '0004_alter_emiratestangermed_heure_prelevement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emiratestangermed',
            name='heure_prelevement',
            field=models.CharField(choices=[('08:00', '8:00 AM'), ('16:00', '16:00 PM')], max_length=5),
        ),
    ]
