# Generated by Django 5.0.7 on 2024-07-23 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emirate', '0006_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emiratestangermed',
            name='heure_prelevement',
            field=models.CharField(blank=True, choices=[('08:00', '8:00 AM'), ('16:00', '16:00 PM')], max_length=5),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emirate.customuser'),
        ),
    ]
