# Generated by Django 5.0.7 on 2024-07-23 15:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emirate', '0007_alter_emiratestangermed_heure_prelevement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_prelevement', models.CharField(blank=True, default='08:00', max_length=5)),
                ('q1_clim_hvac', models.FloatField(blank=True, null=True)),
                ('q2_local_de_charge', models.FloatField(blank=True, null=True)),
                ('q7_eclairage_z1', models.FloatField(blank=True, null=True)),
                ('q8_admin', models.FloatField(blank=True, null=True)),
                ('q9_eclairage_z2', models.FloatField(blank=True, null=True)),
                ('q10_eclairage_z3', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tac',
                'verbose_name_plural': 'Tacs',
            },
        ),
        migrations.RemoveField(
            model_name='emiratestangermed',
            name='Date',
        ),
        migrations.AddField(
            model_name='emiratestangermed',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
