# Generated by Django 5.0.7 on 2024-07-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emirate', '0008_tac_remove_emiratestangermed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tac',
            name='tgbt',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
