# Generated by Django 5.0.7 on 2024-07-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emirate', '0009_tac_tgbt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emiratestangermed',
            name='heure_prelevement',
            field=models.CharField(blank=True, choices=[('08:00', '8:00 AM'), ('16:00', '4:00 PM')], max_length=5),
        ),
    ]
