# Generated by Django 5.0.7 on 2024-07-25 10:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emirate', '0010_alter_emiratestangermed_heure_prelevement'),
    ]

    operations = [
        migrations.AddField(
            model_name='emiratestangermed',
            name='date_and_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tac',
            name='date_and_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
