# Generated by Django 5.0.7 on 2024-08-04 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emirate', '0011_emiratestangermed_date_and_time_tac_date_and_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emiratestangermed',
            options={'verbose_name': 'Emirates Tangermed', 'verbose_name_plural': 'TANGER MED'},
        ),
        migrations.AlterModelOptions(
            name='tac',
            options={'verbose_name': 'Tac', 'verbose_name_plural': 'TAC'},
        ),
    ]
