# Generated by Django 5.0.7 on 2024-08-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emirate', '0012_alter_emiratestangermed_options_alter_tac_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tac',
            name='heure_prelevement',
            field=models.CharField(choices=[('08:00', '8:00 AM'), ('16:00', '4:00 PM')], default='08:00', max_length=5),
        ),
    ]
