# Generated by Django 5.0.6 on 2024-08-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emirate', '0013_alter_tac_heure_prelevement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tac',
            name='heure_prelevement',
            field=models.CharField(choices=[('08:00', '8:00 AM')], default='08:00', max_length=5),
        ),
    ]
